### ISSUE TITLE
Always says "Cannot find executable file of Emacs"

### ISSUE THREAD

**Issue by kuanyen** [GregTrevellick/OpenInApp.Launcher#1]
>Tested under Windows 10 / Visual Studio Community 2017.

I've input the executable path of Emacs manually (I pretty sure it exists because I'm just set this as a shortcut on my desktop and using it everyday.):
![default](https://user-images.githubusercontent.com/20762725/28602251-9bb782bc-71ef-11e7-8a7c-dfb19a0ca58a.png)
But after applying settings, and right click -> open in Emacs:
![default](https://user-images.githubusercontent.com/20762725/28602282-d0f5071a-71ef-11e7-8288-aeca678d1746.png)
It still say not found the executable file.
![default](https://user-images.githubusercontent.com/20762725/28602327-f94ab016-71ef-11e7-81dd-b01493dceb98.png)
Then I open the option UI to confirm what happened, but found the executable path was rolled back to default......
![default](https://user-images.githubusercontent.com/20762725/28602376-488f8282-71f0-11e7-810f-9aa592b84fc7.png)

**Comment by GregTrevellick** [comment]
Hi Yen, I will look into this issue in the next few days. 

Thanks for raising it, Greg

**Comment by GregTrevellick** [comment]
Yen, sorry for the delay, but what is the version number of the extension you are using please ?

**Comment by sjrdc** [comment]
Hi Greg,
I have the same issue here; I'm using version 1.1.41 of the extension
thanks,
Sjoerd

**Comment by GregTrevellick** [comment]
Fixed in v1.1.47. 

Due to the nature of the bug you may need to set the path in your VS options, exit and restart VS before attempting to open a file in emacs.

**Comment by GregTrevellick** [comment]
Issue fixed in v1.1.52, now published to VS Marketplace
