### ISSUE TITLE
"Open In Emacs" doesn't work - can't find runemacs executable

### ISSUE THREAD

**Issue by MikeTheGreat** [GregTrevellick/OpenInApp.Launcher#11]
"Open In Emacs" doesn't work in VS 2017 (Community Edition).  Whenever I try I get the following error:

![image](https://user-images.githubusercontent.com/551619/45338428-0586f600-b542-11e8-9579-cb5af4474e9c.png)

When I browse to the runemacs.exe file and select I get the message:

![image](https://user-images.githubusercontent.com/551619/45338489-51d23600-b542-11e8-874c-24a7a634a5af.png)

When I open up Tools -> Options, then Open In Emacs -> General it lists just 'Emacs' as the "Application path to runemacs.exe".  If I fix it I still get the above two error messages

**Comment by MikeTheGreat** [comment]
It looks like this one bug is the same as #1 .  When I put the path into the Tools->Options and restart VS the path at least 'sticks' (it doesn't disappear) but it still doesn't launch emacs

**Comment by GregTrevellick** [comment]
Hi Mike - Thanks for raising this. I will look into the issue when I have some free time, Greg

**Comment by GregTrevellick** [comment]
Issue fixed in v1.1.52, now published to VS Marketplace
