### ISSUE TITLE
Unexpected error: Visual Studio 2019 (V 16.5.0)

### ISSUE THREAD

**Issue by kemmeter** [GregTrevellick/OpenInApp.Launcher#15]
Hi,

I wanted to try out you plugin, but when I try to open a .md file it throws an unexpected error.

Evaluation Markdown Monster V 1.21.4

![image](https://user-images.githubusercontent.com/2773564/77147381-5eb3dc00-6a8d-11ea-99a7-8ad65f38482b.png)

![image](https://user-images.githubusercontent.com/2773564/77147365-56f43780-6a8d-11ea-8bbe-97df383687bc.png)

![image](https://user-images.githubusercontent.com/2773564/77147233-18f71380-6a8d-11ea-8de0-255ed07eaa11.png)

**Comment by GregTrevellick** [comment]
Thanks Robert - I _can_ recreated this bug so will take a look when I get the time.
