### ISSUE TITLE
2013 Problem

### ISSUE THREAD

**Issue by GrantFromCodecademy** [GregTrevellick/OpenInApp.Launcher#2]
Hi. You probably heard from me before. What I'm using requires the 2013 version of Visual Studio. I can't seem to enable/install your "Open In Paint.net" extension. When I double-click on the vsix it says it can't be installed to any currently installed device.

**Comment by GregTrevellick** [comment]
Hi Grant - I was able to successfully install a new version of "Open In Paint.net" extension, via Visual Studio's "Extensions and Updates" manager window.

Were you using "Extensions and Updates" or manually installing ?

I would suggest you check if any other extensions can be installed - a similar extension to try with can be found at https://marketplace.visualstudio.com/items?itemName=MadsKristensen.OpeninSublimeText

Greg

**Comment by GrantFromCodecademy** [comment]
That won't install either... I'm assuming I'm probably messing something up. Would you mind making a video of how to install this extension for 2013? If it's not too much of a trouble

**Comment by GregTrevellick** [comment]
Try this https://msdn.microsoft.com/en-us/library/ff852054(v=vs.120).aspx

**Comment by GregTrevellick** [comment]
Issue fixed in v1.1.52, now published to VS Marketplace
