### ISSUE TITLE
 I want write a extension and dont know how to write

### ISSUE THREAD

**Issue by qizhoward** [GregTrevellick/OpenInApp.Launcher#3]

**Comment by GregTrevellick** [comment]
Hi Qiz - are you looking to learn how to create extensions generally ? Or is it just that you need Open in PhotoShop within Visual Studio ?

The reason I ask is that I can create Open in PhotoShop for you in a few hours, but if you want to learn yourself then I won't create it and will help you create it.

Greg

**Comment by qizhoward** [comment]
Excuse me
I know yours mean... 
thanks

**Comment by qizhoward** [comment]
thanks
